import { Router } from 'express';
import user from '../v1/routes/user.routes';
import auth from '../v1/routes/auth.routes';
import roles from '../v1/routes/roles.routes';
import rolePermissions from '../v1/routes/rolePermissions.routes';
import permissions from '../v1/routes/permissions.routes';
import company from '../v1/routes/company.routes';
import attendance from '../v1/routes/attendance.routes';
import departments from '../v1/routes/departments.routes';
import designations from '../v1/routes/designations.routes';
import shifts from '../v1/routes/shifts.routes';
import leaveTypes from '../v1/routes/leaveTypes.routes';
import leaveApplications from '../v1/routes/leaveApplications.routes';
import leaveBalances from '../v1/routes/leaveBalances.routes';
import salaryStructures from '../v1/routes/salaryStructures.routes';
import payrollProcessing from '../v1/routes/payrollProcessing.routes';
import salarySlips from '../v1/routes/salarySlips.routes';
import hiringStages from '../v1/routes/hiringStages.routes';
import attachmentTypes from '../v1/routes/attachmentTypes.routes';
import jobPostings from '../v1/routes/jobPostings.routes';
import candidates from '../v1/routes/candidates.routes';
import loginHistory from '../v1/routes/loginHistory.routes';
import apiTokens from '../v1/routes/apiTokens.routes';
import approvalWorkflows from '../v1/routes/approvalWorkflows.routes';
import notifications from '../v1/routes/notifications.routes';
import auditLogs from '../v1/routes/auditLogs.routes';
import settings from '../v1/routes/settings.routes';
import reports from '../v1/routes/reports.routes';
import importExport from '../v1/routes/import-export.routes';
import workflow from '../v1/routes/workflow.routes';
import approvalWorkflowSetup from '../v1/routes/approvalWorkflowSetup.routes';

const routes = Router();

routes.use('/v1', auth);
routes.use('/v1', user);
routes.use('/v1', roles);
routes.use('/v1', rolePermissions);
routes.use('/v1', permissions);
routes.use('/v1', company);
routes.use('/v1', attendance);
routes.use('/v1', departments);
routes.use('/v1', designations);
routes.use('/v1', shifts);
routes.use('/v1', leaveTypes);
routes.use('/v1', leaveApplications);
routes.use('/v1', leaveBalances);
routes.use('/v1', salaryStructures);
routes.use('/v1', payrollProcessing);
routes.use('/v1', salarySlips);
routes.use('/v1', hiringStages);
routes.use('/v1', attachmentTypes);
routes.use('/v1', jobPostings);
routes.use('/v1', candidates);
routes.use('/v1', loginHistory);
routes.use('/v1', apiTokens);
routes.use('/v1', approvalWorkflows);
routes.use('/v1', notifications);
routes.use('/v1', auditLogs);
routes.use('/v1', settings);
routes.use('/v1', reports);
routes.use('/v1', importExport);
routes.use('/v1', workflow);
routes.use('/v1', approvalWorkflowSetup);

export default routes;
